[project]
name = "mlnetst"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anndata==0.11.4",
    "matplotlib==3.10.1",
    "networkx==3.4.2",
    "numba==0.61.2",
    "numpy==2.2.5",
    "pandas==2.2.3",
    "pyjulia==0.0.6",
    "seaborn==0.13.2",
    "torch==2.7.0",
]
